version = 0.1

[default.validate.parameters]
lint = true

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "web-back-sam"
resolve_s3 = true
s3_prefix = "web-back-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.sync.parameters]
watch = true
